### ISSUE TITLE
Merge request for list library methods and lemmas

### ISSUE THREAD

**Issue by ravimad** [epfl-lara/leon#101]
I have added some methods and lemmas to list library. I do not use a fork of Leon (because I already have a fork that uses a older version of leon), so I cannot give a pull request. 
But, the following can be merged easily merged with leon (it is made on top of the recent leon commit).
https://github.com/ravimad/leon2015/commit/73289a87264db4f94ab215ef788b5f354bf778ca

**Comment by colder** [comment]
Merged! Thanks
