### ISSUE TITLE
Leon fails to verify simple list filtering

### ISSUE THREAD

**Issue by liufengyun** [epfl-lara/leon#106]
While doing SAV course project, we found Leon failed to verify following code:

```Scala
  def test(list: List[BigInt], f: BigInt => Boolean): List[BigInt] = {
    list.filter(f)
  } ensuring { res =>
    res.forall(f) && list.forall(e => res.contains(e) == f(e))
  }
```

This may not necessarily be a bug, we report here just to let you know it.

**Comment by samarion** [comment]
This is indeed not a bug, but rather a limitation of Leon (though in general, this would be quite hard to prove automatically). The first part of the the postcondition (namely `res.forall(f)`) is easily proved by Leon thanks to an identical invariant on the definition of `forall` in `leon.collection.List`. In the second case, things get a bit more difficult.

It would be difficult to explain tersely why the condition cannot be proved by Leon, but the main factors are the lack of inductive invariants and the fact that the function `e => res.contains(e) == f(e)` is closed over `res` and it is therefore impossible to specify an invariant as this would require the support of invariants on function classes, or function shapes.

However, what Leon can prove is:
```scala
@induct
def test2(list: List[BigInt], f: BigInt => Boolean): Boolean = {
  list.filter(f).content ++ list.filter(x => !f(x)).content == list.content
}.holds

@induct
def test3(list: List[BigInt], f: BigInt => Boolean): Boolean = {
  list.filter(f).size + list.filter(x => !f(x)).size == list.size
}.holds
```
which are pretty good as well :)
Note the use of the `@induct` notation that tells both `test2` and `test3` that they are inductive over their `list` parameter, and thus provides Leon with the required invariants to build the proof.

**Comment by liufengyun** [comment]
@samarion thanks a lot for your excellent explanation, it makes sense to me now.
