### ISSUE TITLE
Cryptic error message: "Don't know what to do with this. Not purescala?"

### ISSUE THREAD

**Issue by olafurpg** [epfl-lara/leon#107]
The following code produces the error message: "Don't know what to do with this. Not purescala?"
```scala
import leon.lang._
import leon.annotation._

sealed abstract class Cell
case object WhiteCell extends Cell
```
Moving the class definition into a module

```scala
import leon.lang._
import leon.annotation._

object Foo {
  sealed abstract class Cell
  case object WhiteCell extends Cell
}
```
fixes the issue.

**Comment by olafurpg** [comment]
Git blame points at @colder 

9c7e02b5 src/main/scala/leon/frontends/scalac/CodeExtraction.scala (Etienne Kneuss              2014-02-06 13:38:09 +0100  870)           outOfSubsetError(tree, "Don't know what to do with this. Not purescala?");

**Comment by manoskouk** [comment]
Fixed. The problem was that case objects in top-level were handled as module objects.
