### ISSUE TITLE
evaluation and verification don't agree on modulo

### ISSUE THREAD

**Issue by samuelgruetter** [epfl-lara/leon#108]
Consider this:

```scala
import leon.lang._

object Test {
  def m = BigInt(-1) % 3
  
  def claim1 = {
    m == 2
  }.holds
  
  def claim2 = {
    m == -1
  }.holds
}
```

Verification says that `claim1` is invalid and `claim2` is valid. That's what I'd expect, because as mentioned [here](https://github.com/epfl-lara/leon/blob/06ad7d4a317ddbfc1d84b55be6c403b1dd339449/src/main/scala/leon/purescala/Expressions.scala#L328), leon follows Scala/Java and treats '%' as remainder, not modulo.

But running with `--eval`, I get

```
[  Info  ]  - Evaluating m
[  Info  ]   => 2
```

which contradicts the verification results.

Tested on latest commit on master (06995588538a7a41a35eb2f2188986a2755eec07).

**Comment by samuelgruetter** [comment]
FYI I came accross this while fixing the problems that the termination checker found on the List library:

```
[  Info  ] - List$chunk0                    ✗ NoGuarantee                   
[  Info  ] - List$chunks                    ✗ NoGuarantee    

[  Info  ] - List$insertAt                  ✗ Non-terminating for call: List$insertAt(List[T](),-1,List(T#1))
[  Info  ] - List$replaceAt                 ✗ Non-terminating for call: List$replaceAt(List[T](),-1,List(T#1))
[  Info  ] - List$rotate                    ✗ Non-terminating for call: List$rotate(List[T](),1)
```

I've fixed all except `rotate`, because I'd like to use modulo there.

**Comment by regb** [comment]
Thanks for the bug report. There was indeed an issue in the code generation for BigInt. The code gen was using the `mod` operator on Java BigInteger, which has the mathematical semantics of modulo and not the Scala one. This is now fixed in master.
