### ISSUE TITLE
ListSpecs.reverseIndex does not terminate

### ISSUE THREAD

**Issue by larsrh** [epfl-lara/leon#129]
In the body, there's the recursive call `reverseIndex[T](l,i)` which is identical to the initial invocation. `--termination` confirms that there is a counterexample. I tried fixing it, but to no avail so far.

**Comment by vkuncak** [comment]
This function is there for the purpose of a proof hint. A non-terminating proof hint is possibly unsound, so this should just be commented out and an explanation warning put into comment. AFAIK is not used anywhere whatsoever.

**Comment by larsrh** [comment]
The problem is that, as far as I can tell, without the hint, Z3 cannot find the proof, even when the function is annotated with `@induct`.
