### ISSUE TITLE
Closures inside case classes

### ISSUE THREAD

**Issue by jad-hamza** [epfl-lara/leon#155]
The theorem in this example https://leon.epfl.ch#link/97f9f0f73378d23ca2eee6f7806dbfb7-1 is Invalid according to leon (github version), while it should be valid.

Defining the variable client as given in the commentary makes leon say (correctly) that the theorem is valid.

For some reason, on leon-web, this issue doesn't appear (github version, or online version).

**Comment by manoskouk** [comment]
Thanks for reporting.

@samarion I think you have mentioned this problem before, no?

**Comment by samarion** [comment]
I'm not quite sure what's happening. Closures can't be contained in ADTs 
that are free in the formula but this should not be the case here.
Something is probably going on with the field source transform. I'll 
take a look, but I'm already on a bug with quantifiers for now...

**Comment by samarion** [comment]
Fixed in b0984a4
