### ISSUE TITLE
List.find(lambda) is of type <untyped>

### ISSUE THREAD

**Issue by BLepers** [epfl-lara/leon#204]
Maybe related to #203 .

Small  example:

      import leon.collection._
      import leon.lang._

      object Scheduler {
        case class Core(var tasks: List[BigInt], var current: Option[BigInt]) {
        }

        def willBeScheduled(c: Core, j: BigInt, i: BigInt) : Unit = {
           require(!c.tasks.isEmpty)
           require(c.tasks.find(j) == Some(i))

           while(c.current != Some(j)) {
              c.current = c.tasks.find((i:BigInt) => i == j);
           }
        }
      }

==>

      java.lang.AssertionError: assertion failed: lt$28 == lt$27.tasks.find(lambda$0) is not of type Boolean. lt$28 == lt$27.tasks$0.find$3(lambda$0) is of type <untyped>
            lt$28 is of type Option$0[Task$0]
            lt$27.tasks$0.find$3(lambda$0) is of type <untyped>
              lt$27.tasks$0 is of type List$0[Task$0]
                lt$27 is of type Core$0

**Comment by MikaelMayer** [comment]
What is the type of lambda$0 ?

**Comment by BLepers** [comment]
lambda$0 is (i:BigInt) => i == j, so BigInt => Boolean I would say.

**Comment by BLepers** [comment]
My bad, I was running a 2-day old version of Leon. The issue has been fixed in the meanwhile.

Sorry about that...
