### ISSUE TITLE
Moving to GPL from BSD

### ISSUE THREAD

**Issue by sirinath** [epfl-lara/leon#282]
I noticed the license have moved from BSD to GPL. Wondering why? Is it possible to be switch back to BSD.

**Comment by MikaelMayer** [comment]
It is possible to add other licenses, but for that you need to contact [Viktor Kuncak](http://icwww.epfl.ch/~kuncak/).
Note that this is Leon and not Scala.

**Comment by sirinath** [comment]
I know it is not Scala but all the program verification stuff is now GPL which is a bummer.
