### ISSUE TITLE
No guard against circular logic proofs

### ISSUE THREAD

**Issue by samarion** [epfl-lara/leon#80]
Ensuring clauses that create circular logic should be disallowed at some point during verification.
For example:
```scala
def commutative(x: Int, y: Int): Int = {
  if (x > y) x else 0
} ensuring { res => res == commutative(y, x) }
```
will be proved valid by Leon!

**Comment by colder** [comment]
Wouldn't this circularity be fine if the function terminates?

**Comment by samarion** [comment]
Yes, I completely forgot to pull the issue once I realized :) Sorry!
