### ISSUE TITLE
[Leon server] Missing 404 handler in leon.epfl.ch

### ISSUE THREAD

**Issue by olafurpg** [epfl-lara/leon#94]
Visit a random url, e.g. [leon.epfl.ch/docs](http://leon.epfl.ch/docs), and you get an error page
![screen shot 2015-05-04 at 15 21 59](https://cloud.githubusercontent.com/assets/1408093/7454156/5f79a208-f271-11e4-81ff-46f603566d35.png)

I suppose there's missing a [`onHandlerNotFound`](https://www.playframework.com/documentation/2.3.x/ScalaGlobal) definition in the Global object.

**Comment by colder** [comment]
This is fixed in the leon-web repo, I will update leon.epfl.ch shortly.

**Comment by olafurpg** [comment]
Great! I suggest however that you create a useful 404 page instead of always returning a blank 303 redirect to the homepage. This is considered a good practice by [Google](https://support.google.com/webmasters/answer/93641?hl=en), for example. This will also become essential when you update the docs and they accumulate some (dead) links.

You could also let `leon.epfl.ch/docs` 301 redirect to `leon.epfl.ch/doc`. I think many developers, like myself, are likely to guess the url instead of searching for the link on the home page.
