### ISSUE TITLE
leon.collection.List.foldRight inconsistent with scala.collection.immutable.List.foldRight

### ISSUE THREAD

**Issue by olafurpg** [epfl-lara/leon#98]
The signature of `scala.collection.immutable.List.foldRight` is
```scala
  override def foldRight[B](z: B)(op: (A, B) => B): B
```
while for `leon.collection.List.foldRight` it's
```scala
  def foldRight[R](f: (T,R) => R)(z: R): R
```
It would be nice to have the two consistent with each other.

**Comment by colder** [comment]
Merged, thanks
