### ISSUE TITLE
leon.lang.Map.getOrElse missing

### ISSUE THREAD

**Issue by olafurpg** [epfl-lara/leon#99]
The method [`Map.getOrElse`](http://www.scala-lang.org/api/current/index.html#scala.collection.Map@getOrElse%28key:A,default:=%3EB%29:B) is missing in `leon.lang.Map`.

**Comment by olafurpg** [comment]
Also `+`

**Comment by colder** [comment]
Map.+/getOrElse/get is now available in 1b3e61b

Option has been moved to leon.lang, where it belongs.
